version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  triangle_class_build_deploy:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          args: pytest
      - run:
          name: Run Test
          command: |
            cd HW02a\ Testing\ Legacy\ Problem/
            pytest --junitxml=test-results/junit.xml TestTriangle.py
      - store_test_results:
          path: HW02a Testing Legacy Problem/test-results
workflows:
  ssw567:
    jobs:
      - triangle_class_build_deploy
